[[pages]]
path = "/"
screenshotTimestamp = "2026-03-30T15:35:01Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/1IoCqVl"

[[pages]]
path = "/player/profile"
screenshotTimestamp = "2026-03-30T11:18:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/wdWAK7z"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-03-30T15:25:50Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/let20Jh"

[[pages]]
path = "/leaderboard"
screenshotTimestamp = "2026-03-30T11:43:47Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/QOihjfk"

[[pages]]
path = "/matches"
screenshotTimestamp = "2026-03-30T11:43:49Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/8ZZxa0j"

[[pages]]
path = "/register"
screenshotTimestamp = "2026-03-30T15:58:15Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/iTPeZY0"

[[pages]]
path = "/franchise/dashboard"
screenshotTimestamp = "2026-03-30T13:58:27Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/db11e811-716b-4da3-a1ab-81fc58ae468d/75923014-9c67-49be-b6e4-8c04b586c844/rLt3GKK"
